Update README.md
openshift-pipelines/tektoncd-catalog pull request #47
Opened 2023-09-21 06:55 UTC by Aneesh-M-Bhat

2023-09-21 07:03 UTC, Senjuti256 reviewed
LGTM.

2023-09-25 09:37 UTC, vdemeester commented on README.md
> +## Using Tekton Resolvers
I think it would be even more interesting to show the example in a `Pipeline` (+`PipelineRun`) as this should be 99% of use cases for most tasks.

2023-09-28 06:44 UTC, otaviof requested changes
Good progress! I've added a few things to changes, please consider.

2023-09-28 06:44 UTC, otaviof commented on README.md
> +This section explains how to use the tasks supported in this repository with the help of various tools like Tekton Resolvers as well as Pipelines as Code.
Could you please add links to the Tekton Resolvers documentation?

2023-09-28 06:44 UTC, otaviof commented on README.md
> +Note: Add either a secret or update the service account with the git credentials
For this repository no credentials are needed, so we may skip this part.

2023-09-28 06:44 UTC, otaviof commented on README.md
> +- PipelineRun: tkn pipeline start example-pipeline --workspace="name=source,claimName=test,subPath=source" --showlog
Let's have each command to be executed as a code block, please. Easier to recognize as a shell command and to copy-and-paste.

2023-09-28 06:44 UTC, otaviof commented on README.md
> +    pipelinesascode.tekton.dev/max-keep-runs: "5"
Please use only two spaces for YAML content, and also, add hints to describe where the attribute is located, i.e.:

```yaml
metadata:
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
```

2023-09-28 06:44 UTC, otaviof commented on README.md
> +After adding the Tasks to the cluster, you can use them as needed for other resources
You could replace this section with a straightforward `kubectl apply -f https://github.com/...` example. There's no real need to clone this repository.

Also, keep watchful to point users to the `p` branch directly.

2023-10-16 05:57 UTC, otaviof commented
/lgtm

Let's continue to work on this text, that's a good step forward 👍

2023-10-16 06:00 UTC, otaviof commented
/approve

2023-10-16 06:02 UTC, merged